Implement rogue cars, as well as logic for parking spaces
educationallylimited/parking pull request #22
Opened 2018-06-01 01:26 UTC by uptonfunk

This implements rogue agents and their behaviour, and logic for parking lots that will turn away cars when full

2018-06-01 13:33 UTC, bensimner commented on parking/shared/clients.py
> -            logger.info("message recieved as expected: '{}'".format(message_type))
Maybe it would be better to demote these to logger.debug or something rather than outright removing them?

Especially for the success log.

2018-06-01 13:49 UTC, bensimner commented on simulation/simulation.py
> +        return wsmodels.Location(x / (SCALE), y / (SCALE))
I don't know why you put brackets around this.

2018-06-01 13:50 UTC, bensimner commented on simulation/simulation.py
> +        return (loc.latitude * (SCALE), loc.longitude * (SCALE))
Hmm, this is backwards isn't it? Latitude is north/south measurement, and I took that to be the y-axis.

2018-06-03 11:36 UTC, HarveyHunt requested changes

2018-06-03 11:36 UTC, HarveyHunt commented on parking/shared/clients.py
> +            logger.info("server error while updating lot availability for lot number " + str(lot_id))
Maybe this should be a ```logger.warning()```?

2018-06-03 11:36 UTC, HarveyHunt commented on simulation/simulation.py
> +        self.lotdict = {}
Why do we need both lotdict and lots? You could access all the lots in ```lotdict``` using ```lotdict.values()```

2018-06-03 11:36 UTC, HarveyHunt commented on simulation/simulation.py
> +                 no_rogues, width, height, parking_lot_seed, car_seed, max_time, app_url):
Maybe use ```num_rogues``` instead, as ```no_rogues``` sounds like a boolean flag that enables / disables rogues.

2018-06-03 11:36 UTC, HarveyHunt commented on simulation/simulation.py
> +            self.rogue_tasks.append(asyncio.ensure_future(rogue_routine(rogue_start + i/10, loc, dest, self)))
It'd be nice to split this logic into a separate function

2018-06-03 11:36 UTC, HarveyHunt commented on simulation/simulation.py
> +                bestLot = ilot
Maybe this is too optimistic for rogue cars? They might not know the location of nearby lots this accurately

2018-06-03 11:36 UTC, HarveyHunt commented on simulation/simulation.py
> +        bestDistance = 10000000000000
```sys.maxsize``` might be clearer

2018-06-03 11:36 UTC, HarveyHunt commented on simulation/simulation.py
> +
Should we handle the case where ```bestLot is None```?

2018-06-03 11:36 UTC, HarveyHunt commented on simulation/simulation.py
> +        if (not(isinstance(self.lot.capacity, int))) or (not(isinstance(available, int))):
These brackets are pretty crazy, you could instead do:

```if not isinstance(self.lot.capacity, int) or not isinstance(available, int):```

2018-06-03 11:36 UTC, HarveyHunt commented on simulation/simulation.py
> +        self.attempts = []
What are the attempts for?

2018-06-03 11:36 UTC, HarveyHunt commented on simulation/simulation.py
> +                await self.client.update_available(self.lot.id, self.available - 1)
The return value from the backend should be checked for an error.

2018-06-03 11:36 UTC, HarveyHunt commented on simulation/simulation.py
> +                await self.client.update_available(self.lot.id, self.available + 1)
The return value from the backend should be checked for an error.

2018-06-03 11:36 UTC, HarveyHunt commented on simulation/simulation.py
> +        await self.client.update_price(self.lot.id, new_price)
Some error handling would be good

2018-06-03 11:39 UTC, HarveyHunt commented
I've given the code a quick review, I don't want to get bogged down in stylistic stuff given how close we are to the deadline.

I think that you're handling lat / long backwards though.

It'd be great if you could fix the tests and flake8 stuff, then we'll merge. :+1:

2018-06-05 10:06 UTC, bensimner commented on simulation/simulation.py
> +        bestDistance = 10000000000000
float('inf')

2018-06-05 11:18 UTC, merged